exp_mode: 0
width: 2064
height: 1544
left_margin: 1561
top_margin: 1046
right_margin: 850
bottom_margin: 370
max_distance: 1182
min_distance: 1090
hand_template_size: 500
finger_width: 10
finger_height: 30
gripper_width: 30
rotation_step: 45
depth_step: 50
hand_depth: 30
dismiss_area_width: 100
plane_distance: 0.025
length_thre: 15
distance_thre: 3
sliding_size: 125
sliding_stride: 25
compressed_size: 250
