# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynpick.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdynpick.proto\"\t\n\x07Nothing\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x62\n\x07\x44ynPick\x12\x18\n\x03get\x12\x08.Nothing\x1a\x05.Data\"\x00\x12\x1c\n\x04save\x12\x08.Nothing\x1a\x08.Nothing\"\x00\x12\x1f\n\x07save_ok\x12\x08.Nothing\x1a\x08.Nothing\"\x00\x62\x06proto3')



_NOTHING = DESCRIPTOR.message_types_by_name['Nothing']
_DATA = DESCRIPTOR.message_types_by_name['Data']
Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'dynpick_pb2'
  # @@protoc_insertion_point(class_scope:Nothing)
  })
_sym_db.RegisterMessage(Nothing)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'dynpick_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

_DYNPICK = DESCRIPTOR.services_by_name['DynPick']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTHING._serialized_start=17
  _NOTHING._serialized_end=26
  _DATA._serialized_start=28
  _DATA._serialized_end=48
  _DYNPICK._serialized_start=50
  _DYNPICK._serialized_end=148
# @@protoc_insertion_point(module_scope)
