# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nxtrobot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enxtrobot.proto\"\x07\n\x05\x45mpty\"P\n\x06Status\x12\"\n\x05value\x18\x01 \x01(\x0e\x32\x13.Status.StatusValue\"\"\n\x0bStatusValue\x12\t\n\x05\x45RROR\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\"\x19\n\tSendValue\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1b\n\x0bReturnValue\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x90\x06\n\x03Nxt\x12\"\n\rcheckEncoders\x12\x06.Empty\x1a\x07.Status\"\x00\x12\x1c\n\x07servoOn\x12\x06.Empty\x1a\x07.Status\"\x00\x12\x1d\n\x08servoOff\x12\x06.Empty\x1a\x07.Status\"\x00\x12\x1e\n\tgoInitial\x12\x06.Empty\x1a\x07.Status\"\x00\x12\x1e\n\tgoOffPose\x12\x06.Empty\x1a\x07.Status\"\x00\x12(\n\x0egetJointAngles\x12\x06.Empty\x1a\x0c.ReturnValue\"\x00\x12\'\n\x0esetJointAngles\x12\n.SendValue\x1a\x07.Status\"\x00\x12$\n\x0bplayPattern\x12\n.SendValue\x1a\x07.Status\"\x00\x12%\n\x10\x63loseHandToolLft\x12\x06.Empty\x1a\x07.Status\"\x00\x12%\n\x10\x63loseHandToolRgt\x12\x06.Empty\x1a\x07.Status\"\x00\x12$\n\x0fopenHandToolLft\x12\x06.Empty\x1a\x07.Status\"\x00\x12$\n\x0fopenHandToolRgt\x12\x06.Empty\x1a\x07.Status\"\x00\x12%\n\x10\x65jectHandToolLft\x12\x06.Empty\x1a\x07.Status\"\x00\x12%\n\x10\x65jectHandToolRgt\x12\x06.Empty\x1a\x07.Status\"\x00\x12&\n\x11\x61ttachHandToolLft\x12\x06.Empty\x1a\x07.Status\"\x00\x12&\n\x11\x61ttachHandToolRgt\x12\x06.Empty\x1a\x07.Status\"\x00\x12,\n\x13setHandAnglesDegRgt\x12\n.SendValue\x1a\x07.Status\"\x00\x12,\n\x13setHandAnglesDegLft\x12\n.SendValue\x1a\x07.Status\"\x00\x12+\n\x12playPatternOfGroup\x12\n.SendValue\x1a\x07.Status\"\x00\x12.\n\x10getJointPosition\x12\n.SendValue\x1a\x0c.ReturnValue\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_SENDVALUE = DESCRIPTOR.message_types_by_name['SendValue']
_RETURNVALUE = DESCRIPTOR.message_types_by_name['ReturnValue']
_STATUS_STATUSVALUE = _STATUS.enum_types_by_name['StatusValue']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'nxtrobot_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'nxtrobot_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

SendValue = _reflection.GeneratedProtocolMessageType('SendValue', (_message.Message,), {
  'DESCRIPTOR' : _SENDVALUE,
  '__module__' : 'nxtrobot_pb2'
  # @@protoc_insertion_point(class_scope:SendValue)
  })
_sym_db.RegisterMessage(SendValue)

ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _RETURNVALUE,
  '__module__' : 'nxtrobot_pb2'
  # @@protoc_insertion_point(class_scope:ReturnValue)
  })
_sym_db.RegisterMessage(ReturnValue)

_NXT = DESCRIPTOR.services_by_name['Nxt']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=18
  _EMPTY._serialized_end=25
  _STATUS._serialized_start=27
  _STATUS._serialized_end=107
  _STATUS_STATUSVALUE._serialized_start=73
  _STATUS_STATUSVALUE._serialized_end=107
  _SENDVALUE._serialized_start=109
  _SENDVALUE._serialized_end=134
  _RETURNVALUE._serialized_start=136
  _RETURNVALUE._serialized_end=163
  _NXT._serialized_start=166
  _NXT._serialized_end=950
# @@protoc_insertion_point(module_scope)
