# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoxi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='phoxi.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bphoxi.proto\"\x07\n\x05\x45mpty\"\x17\n\x07SaveDir\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05MatKW\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x04Pair\x12\r\n\x05\x64\x61ta0\x18\x01 \x01(\x05\x12\r\n\x05\x64\x61ta1\x18\x02 \x01(\x05\"\x1c\n\nPointCloud\x12\x0e\n\x06points\x18\x01 \x01(\x0c\"G\n\x06\x43\x61mImg\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x32\xf5\x01\n\x05Phoxi\x12 \n\x0ctriggerframe\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\"\n\rgettextureimg\x12\x06.Empty\x1a\x07.CamImg\"\x00\x12 \n\x0bgetdepthimg\x12\x06.Empty\x1a\x07.CamImg\"\x00\x12\x1f\n\x06getpcd\x12\x06.Empty\x1a\x0b.PointCloud\"\x00\x12#\n\ngetnormals\x12\x06.Empty\x1a\x0b.PointCloud\"\x00\x12\x1f\n\x0bsaveplyauto\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1d\n\x07saveply\x12\x08.SaveDir\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=22,
)


_SAVEDIR = _descriptor.Descriptor(
  name='SaveDir',
  full_name='SaveDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='SaveDir.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=47,
)


_MATKW = _descriptor.Descriptor(
  name='MatKW',
  full_name='MatKW',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='MatKW.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=70,
)


_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data0', full_name='Pair.data0', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data1', full_name='Pair.data1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=108,
)


_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='PointCloud.points', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=138,
)


_CAMIMG = _descriptor.Descriptor(
  name='CamImg',
  full_name='CamImg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='CamImg.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='CamImg.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CamImg.channel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='CamImg.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SaveDir'] = _SAVEDIR
DESCRIPTOR.message_types_by_name['MatKW'] = _MATKW
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD
DESCRIPTOR.message_types_by_name['CamImg'] = _CAMIMG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

SaveDir = _reflection.GeneratedProtocolMessageType('SaveDir', (_message.Message,), {
  'DESCRIPTOR' : _SAVEDIR,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:SaveDir)
  })
_sym_db.RegisterMessage(SaveDir)

MatKW = _reflection.GeneratedProtocolMessageType('MatKW', (_message.Message,), {
  'DESCRIPTOR' : _MATKW,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:MatKW)
  })
_sym_db.RegisterMessage(MatKW)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), {
  'DESCRIPTOR' : _PAIR,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:Pair)
  })
_sym_db.RegisterMessage(Pair)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUD,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:PointCloud)
  })
_sym_db.RegisterMessage(PointCloud)

CamImg = _reflection.GeneratedProtocolMessageType('CamImg', (_message.Message,), {
  'DESCRIPTOR' : _CAMIMG,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:CamImg)
  })
_sym_db.RegisterMessage(CamImg)



_PHOXI = _descriptor.ServiceDescriptor(
  name='Phoxi',
  full_name='Phoxi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='triggerframe',
    full_name='Phoxi.triggerframe',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='gettextureimg',
    full_name='Phoxi.gettextureimg',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getdepthimg',
    full_name='Phoxi.getdepthimg',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getpcd',
    full_name='Phoxi.getpcd',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_POINTCLOUD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getnormals',
    full_name='Phoxi.getnormals',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_POINTCLOUD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='saveplyauto',
    full_name='Phoxi.saveplyauto',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='saveply',
    full_name='Phoxi.saveply',
    index=6,
    containing_service=None,
    input_type=_SAVEDIR,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PHOXI)

DESCRIPTOR.services_by_name['Phoxi'] = _PHOXI

# @@protoc_insertion_point(module_scope)
