# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoxi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bphoxi.proto\"\x06\n\x04Null\"\x17\n\x07SaveDir\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05MatKW\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x04Pair\x12\r\n\x05\x64\x61ta0\x18\x01 \x01(\x05\x12\r\n\x05\x64\x61ta1\x18\x02 \x01(\x05\"\x1c\n\nPointCloud\x12\x0e\n\x06points\x18\x01 \x01(\x0c\"G\n\x06\x43\x61mImg\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x32\xec\x01\n\x05Phoxi\x12\x1e\n\x0ctriggerframe\x12\x05.Null\x1a\x05.Null\"\x00\x12!\n\rgettextureimg\x12\x05.Null\x1a\x07.CamImg\"\x00\x12\x1f\n\x0bgetdepthimg\x12\x05.Null\x1a\x07.CamImg\"\x00\x12\x1e\n\x06getpcd\x12\x05.Null\x1a\x0b.PointCloud\"\x00\x12\"\n\ngetnormals\x12\x05.Null\x1a\x0b.PointCloud\"\x00\x12\x1d\n\x0bsaveplyauto\x12\x05.Null\x1a\x05.Null\"\x00\x12\x1c\n\x07saveply\x12\x08.SaveDir\x1a\x05.Null\"\x00\x62\x06proto3')



_NULL = DESCRIPTOR.message_types_by_name['Null']
_SAVEDIR = DESCRIPTOR.message_types_by_name['SaveDir']
_MATKW = DESCRIPTOR.message_types_by_name['MatKW']
_PAIR = DESCRIPTOR.message_types_by_name['Pair']
_POINTCLOUD = DESCRIPTOR.message_types_by_name['PointCloud']
_CAMIMG = DESCRIPTOR.message_types_by_name['CamImg']
Null = _reflection.GeneratedProtocolMessageType('Null', (_message.Message,), {
  'DESCRIPTOR' : _NULL,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:Null)
  })
_sym_db.RegisterMessage(Null)

SaveDir = _reflection.GeneratedProtocolMessageType('SaveDir', (_message.Message,), {
  'DESCRIPTOR' : _SAVEDIR,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:SaveDir)
  })
_sym_db.RegisterMessage(SaveDir)

MatKW = _reflection.GeneratedProtocolMessageType('MatKW', (_message.Message,), {
  'DESCRIPTOR' : _MATKW,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:MatKW)
  })
_sym_db.RegisterMessage(MatKW)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), {
  'DESCRIPTOR' : _PAIR,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:Pair)
  })
_sym_db.RegisterMessage(Pair)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUD,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:PointCloud)
  })
_sym_db.RegisterMessage(PointCloud)

CamImg = _reflection.GeneratedProtocolMessageType('CamImg', (_message.Message,), {
  'DESCRIPTOR' : _CAMIMG,
  '__module__' : 'phoxi_pb2'
  # @@protoc_insertion_point(class_scope:CamImg)
  })
_sym_db.RegisterMessage(CamImg)

_PHOXI = DESCRIPTOR.services_by_name['Phoxi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=15
  _NULL._serialized_end=21
  _SAVEDIR._serialized_start=23
  _SAVEDIR._serialized_end=46
  _MATKW._serialized_start=48
  _MATKW._serialized_end=69
  _PAIR._serialized_start=71
  _PAIR._serialized_end=107
  _POINTCLOUD._serialized_start=109
  _POINTCLOUD._serialized_end=137
  _CAMIMG._serialized_start=139
  _CAMIMG._serialized_end=210
  _PHOXI._serialized_start=213
  _PHOXI._serialized_end=449
# @@protoc_insertion_point(module_scope)
